apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore-rest-server
  labels:
    app: petstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstore
  template:
    metadata:
      labels:
        app: petstore
    spec:
      containers:
        - name: app-petstore
          image: petstore/rest-server:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: petstore-rest-server
spec:
  selector:
    app: petstore
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
      nodePort: 30008
