apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore-rest-server
  labels:
    app: petstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstore
  template:
    metadata:
      labels:
        app: petstore
    spec:
      containers:
        - name: app-petstore
          image: __IMAGE__
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: petstore-rest-server
spec:
  selector:
    app: petstore
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      targetPort: 8080
      port: 8080
  externalIPs:
  - 192.168.1.15
#      nodePort: 30008
#  type: LoadBalancer
#  loadBalancerIP: __IP__
