apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore-rest-server
  labels:
    app: petstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstore
  template:
    metadata:
      labels:
        app: petstore
    spec:
      containers:
        - name: app-petstore
          image: __IMAGE__
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: petstore-rest-service
spec:
  selector:
    app: petstore
  ports:
    - name: http
      protocol: TCP
      targetPort: 8080
      port: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: petstore.cstudio.dev
spec:
  rules:
    - host: petstore.cstudio.dev
      http:
        paths:
          - path: /
            backend:
              serviceName: petstore-rest-service
              servicePort: 8080
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: petstore-rest-server
#spec:
#  selector:
#    app: petstore
#  type: NodePort
#  ports:
#    - name: http
#      protocol: TCP
#      targetPort: 8080
#      port: 8080
#    - name: https
#      protocol: TCP
#      port: 443
#      targetPort: 443
#  externalIPs:
#    - 192.168.1.15
#      nodePort: 30008
#  type: LoadBalancer
#  loadBalancerIP: __IP__
#---
#apiVersion: v1
#kind: Endpoints
#metadata:
#  name: petstore-endpoint
#subsets:
#  - addresses:
#      - ip: 0.0.0.0,192.168.1.14
#    ports:
#      - port: 8080
